import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import MissionCard from "../components/MissionCard";

function Mission() {
  const navigate = useNavigate();

  // Parse out the active mission generated by your backend agents
  const mission = JSON.parse(
    localStorage.getItem("mission") || "{}"
  );

  const journey =
    localStorage.getItem("selected_journey") || "Explorer";

  const title =
    mission.title || mission.career || "Career Challenge";

  // Handles any variable fallback configuration from the AI text model safely
  const instruction =
    mission.instruction ||
    mission.question ||
    mission.description ||
    "Read through your active game engine rules and choose the best path forward.";

  const xp =
    mission.xp || mission.xp_reward || 20;

  // FIX: Checks backend 'game_type' first, then falls back to camelCase 'gameType'
  const rawGameType = mission.game_type || mission.gameType || "quiz";
  const gameType = rawGameType.toLowerCase();

  // FIX: Checks backend 'task_type' first, then falls back to camelCase 'taskType'
  const taskType = mission.task_type || mission.taskType || "Virtual";

  const startMission = () => {
    localStorage.setItem("earned_xp", xp);

    localStorage.setItem(
      "current_mission",
      JSON.stringify(mission)
    );

    // 📸 Route directly to scanner view if it is an image validation task
    if (taskType === "Practical" || gameType === "camera") {
      navigate("/camera");
      return;
    }

    // 🎮 Virtual Custom Engine Dynamic Router Switch
    switch (gameType) {
      case "quiz":
        navigate("/quiz");
        break;

      case "simulation":
        navigate("/simulation");
        break;

      case "roleplay":
      case "story":
        navigate("/roleplay");
        break;

      case "creativity":
        navigate("/creativity");
        break;

      case "reaction":
        navigate("/reaction");
        break;

      case "puzzle":
        navigate("/puzzle");
        break;

      case "builder":
        navigate("/builder");
        break;

      case "memory":
        navigate("/memory");
        break;

      case "pattern":
        navigate("/pattern");
        break;

      case "sorting":
        navigate("/sorting");
        break;

      default:
        navigate("/quiz"); // Robust fallback default
    }
  };

  return (
    <motion.div
      className="screen"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
    >
      <MissionCard
        title={title}
        journey={journey}
        instruction={instruction}
        taskType={taskType}
        gameType={
          gameType.charAt(0).toUpperCase() + gameType.slice(1)
        }
        xp={xp}
        onStart={startMission}
      />
    </motion.div>
  );
}

export default Mission;